name: Build Android

permissions:
  contents: read
  pull-requests: write
  
on: 
  workflow_dispatch:
  workflow_call:

  push:
    branches:
      - master
      - main

  pull_request:
    branches:
      - master
      - main

env:
  # NOTE: secrets are only provided in original repo, ideal for conditional logic in forks
  ANDROID_CERTIFICATE_BASE64: ${{ secrets.ANDROID_CERTIFICATE_BASE64 }}
  ANDROID_PRIVATE_KEY_BASE64: ${{ secrets.ANDROID_PRIVATE_KEY_BASE64 }}


jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install Java
        uses: actions/setup-java@v5
        with:
          distribution: 'jetbrains'
          java-version: '25'

      - name: Install SDK
        run: ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --install 'platforms;android-36' 'build-tools;36.1.0' 'ndk;28.2.13676358'

      # Secrets should be the base64 portion of the PEM format
      # (i.e. the stuff between the BEGIN/END lines):
      #
      # -----BEGIN CERTIFICATE-----
      # ... base64-encoded X.509 certificate ...
      # -----END CERTIFICATE-----
      #
      # -----BEGIN PRIVATE KEY-----
      # ... base64-encoded PKCS#8 private key ...
      # -----END PRIVATE KEY-----
      #
      # These can be extracted from a PKCS#12 .keystore file using:
      # openssl pkcs12 -in path/to/.keystore -info -noenc

      - name: Install certificate and private key
        if: env.ANDROID_PRIVATE_KEY_BASE64 != '' && env.ANDROID_CERTIFICATE_BASE64 != ''
        working-directory: Desktop_Interface
        run: |
          echo "$ANDROID_CERTIFICATE_BASE64" | base64 --decode > cert.cer
          echo "$ANDROID_PRIVATE_KEY_BASE64" | base64 --decode > cert.p8

      # The .apk must be signed to be useful.  If the previous step
      # was unsuccessful or skipped, build a debug package which will
      # be signed with debug keys.

      - name: Build Android package
        working-directory: Android_App
        run: |
          APK_BASENAME="Labrador-$(git rev-parse --short HEAD)"
          if [ -e cert.cer ] && [ -e cert.p8 ]; then
            ./gradlew assembleRelease
            ${ANDROID_SDK_ROOT}/build-tools/36.1.0/apksigner sign --in app/build/outputs/apk/release/app-release-unsigned.apk --out ${APK_BASENAME}-release-signed.apk --key cert.p8 --cert cert.cer --verbose
          else
            ./gradlew assembleDebug
            cp app/build/outputs/apk/debug/app-debug.apk ${APK_BASENAME}-debug.apk
          fi

      - name: Upload apk artifacts
        uses: actions/upload-artifact@v4
        with:
          name: asset-apk
          path: Android_App/Labrador*.apk
          compression-level: 0
          if-no-files-found: error
