name: Continuous Release

on:
  workflow_dispatch:

jobs:
  build-linux:
    uses: ./.github/workflows/linux.yml
  build-mac:
    uses: ./.github/workflows/mac.yml
  build-windows:
    uses: ./.github/workflows/windows.yml

  release:
    permissions:
      contents: write
    needs:
      - build-linux
      - build-mac
      - build-windows
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: asset-*
          merge-multiple: true

      - name: Run uploadtool
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          UPLOADTOOL_ISPRERELEASE: 'true'
          UPLOADTOOL_BODY: |-
            ## Linux (including Raspberry Pi)

            The Debian package is still a work in progess.  Please use one of the AppImages.

            The AppImages should be compatible with all modern 64-bit distros.  Download the `aarch64` AppImage for 64-bit ARM computers (e.g. Raspberry Pi), or the `x86_64` AppImage for 64-bit Intel/AMD computers.

            - First make the AppImage file executable by running `chmod +x EspoTek_Labrador*.AppImage`
            - Now you can run it just like any other program or script: `./EspoTek_Labrador*.AppImage`

            If you're running 32-bit, please see the [build instructions](https://github.com/espotek-org/Labrador/wiki/Building-for-32-bit-Linux) or run the [Raspberry Pi bootstrap script](https://github.com/espotek-org/Labrador#raspberry-pi-build).

            ## macOS

            Download `Labrador-<version>.dmg` for macOS 10.13 and later.
            If you are running an older version of macOS, please use the macOS Legacy build below.

            - Drag the Labrador app into `/Applications`
            - Right-click and Open the Labrador app in your `/Applications` directory (you need to right-click and open, you can't just double-click)
            - If you see a warning message, just press the `Open` button to continue
            - That's it, you're done!  From now on you can open by simply double-clicking as you would any other app

            ## Windows

            Download `Labrador-<version>-installer.exe` for Windows 7 or later (32-bit and 64-bit supported).
        run: |
          UPLOADTOOL_BODY="$(echo "$UPLOADTOOL_BODY" | jq -Rsa '.')"
          UPLOADTOOL_BODY="${UPLOADTOOL_BODY%\"}"
          UPLOADTOOL_BODY="${UPLOADTOOL_BODY#\"}"

          wget -N https://github.com/probonopd/uploadtool/raw/master/upload.sh
          chmod +x ./upload.sh
          find . -type f -not -path ./upload.sh -exec ./upload.sh {} +
