name: Build Linux

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-appimage:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            arch: x86_64
          - os: ubuntu-22.04-arm
            arch: aarch64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo apt-get install -y build-essential libfftw3-dev qtbase5-dev libusb-1.0-0-dev libeigen3-dev wget

      - name: Build AppImage
        working-directory: Desktop_Interface
        run: |
          ./make_appimage

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: asset-appimage-${{ matrix.arch }}
          path: Desktop_Interface/Labrador*.AppImage
          compression-level: 0
          if-no-files-found: error

  build-deb:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo apt-get install -y build-essential libfftw3-dev qtbase5-dev libusb-1.0-0-dev libeigen3-dev

      - name: Build Debian package
        working-directory: Desktop_Interface
        run: |
          ./make_deb

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: asset-deb
          path: Desktop_Interface/Labrador*.deb
          compression-level: 0
          if-no-files-found: error
