name: Build Linux

on:
  workflow_dispatch:

jobs:
  build-appimage:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            arch: x86_64
          - os: ubuntu-22.04-arm
            arch: aarch64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo apt-get install -y build-essential libfftw3-dev qtbase5-dev libusb-1.0-0-dev libeigen3-dev wget

      - name: Build AppImage
        working-directory: Desktop_Interface
        run: |
          ./make_appimage

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: appimage-${{ matrix.arch }}
          path: Desktop_Interface/EspoTek_Labrador*.AppImage
          compression-level: 0
          if-no-files-found: error

  build-deb:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo apt-get install -y build-essential libfftw3-dev qtbase5-dev libusb-1.0-0-dev libeigen3-dev

      - name: Build Debian package
        working-directory: Desktop_Interface
        run: |
          ./make_deb

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: deb
          path: Desktop_Interface/EspoTek_Labrador*.deb
          compression-level: 0
          if-no-files-found: error

  release:
    permissions:
      contents: write
    needs:
      - build-appimage
      - build-deb
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: List artifacts
        run: |
          find . -type f

      - name: Run uploadtool
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          UPLOADTOOL_ISPRERELEASE: 'true'
          UPLOADTOOL_SUFFIX: 'Linux'
          UPLOADTOOL_BODY: |-
            EspoTek Labrador software for Linux.  This should be compatible with all modern 64-bit distros.
            If you're running 32-bit Linux, please see the [build instructions](https://github.com/espotek-org/Labrador/wiki/Building-for-32-bit-Linux).

            The Debian package is still a work in progess.  Please use the AppImage:

            - First make the AppImage file executable by running `chmod +x EspoTek_Labrador*.AppImage`
            - Now you can run it just like any other program or script: `./EspoTek_Labrador*.AppImage`
        run: |
          UPLOADTOOL_BODY="$(echo "$UPLOADTOOL_BODY" | jq -Rsa '.')"
          UPLOADTOOL_BODY="${UPLOADTOOL_BODY%\"}"
          UPLOADTOOL_BODY="${UPLOADTOOL_BODY#\"}"

          wget -N https://github.com/probonopd/uploadtool/raw/master/upload.sh
          chmod +x ./upload.sh
          find . -type f -not -path ./upload.sh -exec ./upload.sh {} +
