name: Build Linux

on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies and build AppImage
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository ppa:ubuntu-toolchain-r-test -y
          sudo apt-get update
          sudo apt-get install -y gcc-7 g++-7 libfftw3-dev qt5-default libusb-1.0-0-dev wget
          sudo add-apt-repository ppa:beineri/opt-qt-5.12.9-xenial -y
          sudo apt-get update -qq
          sudo apt-get install -y qt512base
          source /opt/qt*/bin/qt*-env.sh
          export CC=gcc-7
          export CXX=g++-7
          cd Desktop_Interface
          ./make_appimage

      - name: Run uploadtool for Linux
        run: |
          export UPLOADTOOL_SUFFIX="Linux"
          export UPLOADTOOL_BODY="EspoTek Labrador software for Linux. This should be compatible with all modern 64-bit distros. If you're running 32-bit Linux, please see the wiki for build instructions. https://github.com/espotek-org/Labrador/wiki/Building-for-32-bit-Linux"
          wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
          bash upload.sh EspoTek_Labrador*.AppImage
